C $Header:/MITgcm/pkg/BFMcoupler/BFMcoupler_VARDIAGlocal.h,v 1.01
C 2014/04/10
C local variables of diagnostic for BFMcoupler_calc_tendency.f 
C 
      _RL   diaPPG(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaNPP(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaBPP(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaDIC(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaCO2(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaHCO3(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaCO3(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaAc(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diapH(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diapCO2(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF01(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF02(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF03(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF04(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF05(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF06(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF07(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF08(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF09(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF10(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF11(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF12(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaF13(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaxpar(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diawspeed(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaRHOSitu(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
      _RL   diaPCO2atm(1-OLx:sNx+OLx,1-OLy:sNy+OLy,Nr)
